### ISSUE TITLE
[Feature] [Fall] add 3D to frontend

### ISSUE THREAD

**Issue by trexrush** [acmutd/portal-next#72]
Due to time constraints, the initial launch of Portal will not have a welcome page with 3D elements. This issue seeks to fix that during the fall.

- [ ] Home page
   - [ ] Create mr.peechi model
   - [ ] Create importer for 3d models with ThreeJS
   - [ ] Background as 3d? (optional)

**Comment by DedsecKnight** [comment]
Will close these for now
