### ISSUE TITLE
[Feature] Architecture for New Application System

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#96]
**Describe new addition**
Portal v2 is expected to provide an in-house application system, which allows officers to overcome drawbacks that they are facing due to using Typeform. Right now, it is necessary that the user flow and the high-level architecture is consolidated. 

**Task List**
 - [x] Look at the database architecture of new application system in the shared drive and provide feedback.
 - [x] Plan out the user flow and wireframe for mockup. 

**Additional context**
- [Database Architecture of new application system](https://docs.google.com/document/d/13_GOQoMbiZfNmpe3sO06wxHRbKt_7uFhvxXhoUh8m8w)

**Comment by abhiamishra** [comment]
- Looked over the system architecture + some questions to ask @DedsecKnight 
- Some issues that exist with preferences as students, in Projects and Research, have to pick their top 3 preferences - must be added to applications DB
- In addition, I am talking with Roman to fully flesh out the workflow for conflict of a student applying in multiple projects
- A fully fleshed out DB schema should be ready EOD.

**Comment by abhiamishra** [comment]
Questions for @DedsecKnight 

- Officer can see other stuffs from other divisions
    - Does this just mean applicants that have applied to multiple cohorts or all applicants in general? What is all entailed by "other stuffs"?
- Should talk to other directors about how they’re using TypeForm
    - Discuss the applicant or application?
- What is the use of User ID in the "Junction table between person and application". Aren't entryID and formID sufficient? What new information does userID seek to provide?

**Comment by abhiamishra** [comment]
Current ERD Diagram

![Portalv2](https://user-images.githubusercontent.com/52009380/199811635-a7ebf570-25a4-497e-abe2-9ab5013d3565.png)

**Comment by DedsecKnight** [comment]
> Officer can see other stuffs from other divisions

I believe this refer to a potential flaw in that design, which basically allows officers to see responses for all applications. In other words, this means that a Project officer can see responses for Research application regardless whether they are affiliated with Research or not. If this is not an issue for other divisions, feel free to ignore it. 

> Should talk to other directors about how they’re using TypeForm

I believe this has to do with the fact that we need to consult with officers from other division to see what their issues with Typeform Application system are, from which we will know how we can improve it with the new application system. 

> What is the use of User ID in the "Junction table between person and application".

Junction table represents the Many-to-Many relationship between User and Cohort application, meaning that a user can apply to multiple cohort programs and a cohort program can have multiple applicants. The purpose of User ID is so that we can later fetch all applications that a user submitted to along with the status of each application in Portal view. 

> Current ERD Diagram

The diagram looks good to me. A few things I think will be needed for it to work with our current database architecture: 

- The `officer` object is not tied to the `Profile` object, which is currently our source of truth for user data on Portal. The easiest way I can think of to fix this is to add `profileID` field to `officer` table, which will act as a foreign key referring to Profile object. The schema for Profile object can be found below if necessary: 
```
model Profile {
    id               String    @id @default(auto()) @map("_id") @db.ObjectId
    firstName        String
    lastName         String
    email            String    @unique
    netid            String    @unique
    classStanding    String
    major            String
    utdStudent       Boolean
    roles            String[]
    membershipStatus Boolean
    membershipTS     DateTime?
    resume           Boolean
    resumeTS         DateTime?
    user User @relation(fields: [userId], references: [id])
    userId String             @unique @db.ObjectId
    events EventReservation[]
}
```

- Also, in the `officer` object, an officer can also belong to multiple division, so make sure to take that into consideration as well.

**Comment by abhiamishra** [comment]
> I believe this refer to a potential flaw in that design, which basically allows officers to see responses for all applications. In other words, this means that a Project officer can see responses for Research application regardless whether they are affiliated with Research or not. If this is not an issue for other divisions, feel free to ignore it.

This is an issue so it will be fixed.

> I believe this has to do with the fact that we need to consult with officers from other division to see what their issues with Typeform Application system are, from which we will know how we can improve it with the new application system.

I can do this for Research easily - will have to reach out to Projects and Education.

**Comment by abhiamishra** [comment]
~~@DedsecKnight quick question for the user: to me, entryID and userID seem redundant? If we are using userID to find all applications done by that user, what is the use of entryID?~~

~~In the document scheme, it's labeled as the primary key but I think just userID should just be the primary key. What do you think?~~

Nevermind, I read it wrong - it's all good

**Comment by abhiamishra** [comment]
This is the process for resolving conflicts when multiple divisions want an applicant:

> So each division chooses some people it wants to interview, and if multiple divisions choose the same person, then they're interviewed by the division that they ranked higher

**Comment by abhiamishra** [comment]
Updated database app - pending review from @DedsecKnight 
![Portalv2 (1)](https://user-images.githubusercontent.com/52009380/201985666-ed3dd818-a7a8-4386-9198-ef435838eb0a.png)

**Comment by abhiamishra** [comment]
@DedsecKnight - I think I'll just do the user flow since for the wireframe, I'm not really orientated with the design outline of Portalv2.0 nor am I frontend person

**Comment by DedsecKnight** [comment]
Sounds good to me

**Comment by abhiamishra** [comment]
Completed database scheme uploaded here for reference:

[portalv2-database-arch.pdf](https://github.com/acmutd/portal-next/files/10080318/portalv2-database-arch.pdf)

**Comment by abhiamishra** [comment]
Applicant/User userflow

![image](https://user-images.githubusercontent.com/52009380/203689762-ffa693e8-4c0c-4643-a823-a26133bd5ef1.png)

**Comment by abhiamishra** [comment]
Done with both workflows. Need to meet with UI/Frontend designers to hash out how it will look like. Files to be uploaded @ today's meeting

**Comment by abhiamishra** [comment]
https://www.figma.com/file/braXCgUdBVh4DMYrixgXNY/User-Flow-Kit-(Sinan-ARTIS)-(Community)-(Copy)?node-id=9%3A496&t=TSgqi9JW2a58mINt-1
